draft_lab/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
from lab_1.views import index as index_lab1


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2-addon')),
    url(r'^$', RedirectView.as_view(permanent=True,   url='/lab-2/'), name='index')
]

lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index')
]

lab_4/urls.py
from django.conf.urls import url
from .views import index, message_post,message_table
urlpatterns = [
url(r'^$', index, name='index'),
url(r'^add_message', message_post, name='add_message'),
url(r'^result_table', message_table, name='result_table'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10
from lab_1.views import index as index_lab1


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2-addon')),
    url(r'^lab-3/', include(lab_3,namespace='lab-3')),
    url(r'^lab-4/', include(lab_4, namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    url(r'^lab-9/', include(lab_9, namespace='lab-9')),
    url(r'^lab-10/', include(lab_10, namespace='lab-10')),
    url(r'^$', RedirectView.as_view(permanent=True,   url='/lab-9/'), name='index')
]

lab_4/models.py
from django.db import models

# Create your models here.
class Message(models.Model):
    name = models.CharField(max_length=27)
    email = models.EmailField()
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message

lab_4/forms.py
from django import forms

class Message_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }

    name = forms.CharField(label='Nama', required=False, max_length=27, empty_value='Anonymous', widget=forms.TextInput(attrs=attrs))
    email = forms.EmailField(required=False, widget=forms.EmailInput(attrs=attrs))
    message = forms.CharField(widget=forms.Textarea(attrs=attrs), required=True)

lab_4/views.py
from django.http import HttpResponseRedirect
from .forms import Message_Form
from .models import Message
from django.shortcuts import render
from lab_2.views import landing_page_content

    # Create your views here.
response = {'author': "Hilya Auli Fesmia"} #TODO Implement yourname
about_me = ['Tidur','Tidur','Tidur','Makan','Tidur','Makan']


def index(request):
    response['content'] = landing_page_content
    html = 'lab_4/lab_4.html'
    #TODO Implement, isilah dengan 6 kata yang mendeskripsikan anda
    response['about_me'] = about_me
    response['message_form'] = Message_Form
    #response['add_message'] = add_message
    return render(request, html, response)

#def add_message(request):
#    message_post
#    pass

def message_table(request):
    message = Message.objects.all()
    response['message'] = message
    html = 'lab_4/table.html'
    return render(request, html , response)

def message_post(request):
    form = Message_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
        response['email'] = request.POST['email'] if request.POST['email'] != "" else "Anonymous"
        response['message'] = request.POST['message']
        message = Message(name=response['name'], email=response['email'],
        message=response['message'])
        message.save()
        html ='lab_4/form_result.html'
        return render(request, html, response)
    else:
        return HttpResponseRedirect('/lab-4/')

lab_4/templates/lab_4/form_result.html
<<<<<<< HEAD
<!DOCTYPE html>
<style>
    footer {
      position: relative;
      right: 0;
      bottom: 0;
      left: 0;
      padding: 1rem;
      background-color: #efefef;
      text-align: center;
      clear: both;
      z-index: 10;
      height: 5em;
      margin-top: 5em;
    }
</style>

{% extends "lab_4/layout/base.html" %}
{% block title %} Pesan dari {{ name }} {% endblock %}
{% block content %}
<textarea readonly rows="5" class="form-control">&quot;{{message}}&quot;-{{name}} 
    by {{ email }}
</textarea>
{% endblock %}

{% block footer %}
    <p> &copy; {{name}} </p>
=======
<!DOCTYPE html>
<style>
    footer {
      position: relative;
      right: 0;
      bottom: 0;
      left: 0;
      padding: 1rem;
      background-color: #efefef;
      text-align: center;
      clear: both;
      z-index: 10;
      height: 5em;
      margin-top: 5em;
    }
</style>

{% extends "lab_4/layout/base.html" %}
{% block title %} Pesan dari {{ name }} {% endblock %}
{% block content %}
<textarea readonly rows="5" class="form-control">&quot;{{message}}&quot;-{{name}} 
    by {{ email }}
</textarea>
{% endblock %}

{% block footer %}
    <p> &copy; {{name}} </p>
>>>>>>> 5571a6622f332b10d4b93305cc9961eb05854c3e
{% endblock %}

lab_4/templates/lab_4/lab_4.html
<<<<<<< HEAD
<!DOCTYPE html>
{% extends "lab_4/layout/base.html" %}
{% load static %}

{% block content %}
<!--<h1>Portofolio</h1>-->
<head>
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
</head>
<section name="bio">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1231.83 279.94">
    <defs>
      <style>.cls-1,.cls-2{font-size:204px;font-family:Avenir-Black, Avenir;letter-spacing:0.1em;}.cls-1{fill:#FCF8E3;}.cls-2{fill:none;stroke:#000;stroke-miterlimit:10;stroke-width:5px;}
      </style>
    </defs>
    <title>Welcome</title>
    <g id="Layer_2" data-name="Layer 2">
      <g id="Layer_1-2" data-name="Layer 1">
        <text class="cls-1" transform="translate(16.41 186.71)">WELCOME</text>
        <text class="cls-2" transform="translate(5.41 176.71)">WELCOME</text>
      </g>
    </g>
  </svg>
    <!--<h2>Bio</h2>-->
    <p style="text-align:center; font-size:3rem; color:#161616">
        {{content}}
    </p>
</section>

<section name="about_me">
    <h2 style="font-size:4rem; color:#FCF8E3; font-family: Montserrat">Things That I Like</h2>
    <ul style="font-size:2rem">
        {% for ii in about_me %}
        <li> {{ ii }} </li>
        {% endfor %}
    </ul>
</section>
<hr/>
<section name="form">
    <h2 style="text-align: center; font-size:5rem; color:#FCF8E3">It's time to say things out loud.<br>
Are you ready?</br></h2>
<img src="https://www.horoscope.com/images-US/signs/profile-aquarius.png" style="width: 20rem; text-align: center"/>
    <form id="form" method="POST" action="{% url 'lab-4:add_message' %}">
        {% csrf_token %}
        {{ message_form }}
        <br>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
</section>

=======
<!DOCTYPE html>
{% extends "lab_4/layout/base.html" %}
{% load static %}

{% block content %}
<!--<h1>Portofolio</h1>-->
<head>
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
</head>
<section name="bio">
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1231.83 279.94">
    <defs>
      <style>.cls-1,.cls-2{font-size:204px;font-family:Avenir-Black, Avenir;letter-spacing:0.1em;}.cls-1{fill:#FCF8E3;}.cls-2{fill:none;stroke:#000;stroke-miterlimit:10;stroke-width:5px;}
      </style>
    </defs>
    <title>Welcome</title>
    <g id="Layer_2" data-name="Layer 2">
      <g id="Layer_1-2" data-name="Layer 1">
        <text class="cls-1" transform="translate(16.41 186.71)">WELCOME</text>
        <text class="cls-2" transform="translate(5.41 176.71)">WELCOME</text>
      </g>
    </g>
  </svg>
    <!--<h2>Bio</h2>-->
    <p style="text-align:center; font-size:3rem; color:#161616">
        {{content}}
    </p>
</section>

<section name="about_me">
    <h2 style="font-size:4rem; color:#FCF8E3; font-family: Montserrat">Things That I Like</h2>
    <ul style="font-size:2rem">
        {% for ii in about_me %}
        <li> {{ ii }} </li>
        {% endfor %}
    </ul>
</section>
<hr/>
<section name="form">
    <h2 style="text-align: center; font-size:5rem; color:#FCF8E3">It's time to say things out loud.<br>
Are you ready?</br></h2>
<img src="https://www.horoscope.com/images-US/signs/profile-aquarius.png" style="width: 20rem; text-align: center"/>
    <form id="form" method="POST" action="{% url 'lab-4:add_message' %}">
        {% csrf_token %}
        {{ message_form }}
        <br>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
</section>

>>>>>>> 5571a6622f332b10d4b93305cc9961eb05854c3e
{% endblock %}

lab_4/templates/lab_4/table.html
{% extends "lab_4/layout/base.html" %}

    {% block title %} Kumpulan Pesan {% endblock %}

    {% block content %}
    <head>
      <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    </head>
    <!--  Populate semua isi pesan dari model -->
    <table class="table" style="font-family: Montserrat">
        <thead style="font-size:4rem; color:#f6f6f6">
            <th>Nama</th>
            <th>Email</th>
            <th>Pesan</th>
            <th>Dibuat Pada</th>
        </thead>
        <tbody style="font-size: 2rem">
            <!-- TODO, Kalau nama/email anon maka tr classnya jadi warning -->
            {% for i in message %}
            {% if i.name == 'Anonymous' or i.email == 'Anonymous' %}
            <tr class="warning"> {% else %} <tr class="success">
                {% endif %}
                <td> {{i.name}} </td>
                <td> {{i.email}} </td>
                <td> {{i.message}} </td>
                <td> {{i.created_date}} </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% endblock %}